function init() {
    this.combox.addListener(flower.DataGroupEvent.SELECTED_ITEM_CHANGE, function (e) {
        console.log("event:" + e.type);
    });
}

function onSure() {
    var name = this.nameInput.text;
    var id = this.idInput.text;
    if (id == "") {
        software.Alert.show("id 不能为空");
        return;
    }
    this.closePanel();
    var path = this.data.path + "/" + name + "." + this.data.type;
}
