var Rect = (function (_super) {

    __extends(Rect, _super);

    function Rect(data) {
        _super.call(this, data);
    }

    Rect.prototype.init = function () {
        this.show = new flower.Rect();
        var display = this.data.display;
        var keys = display.membersKey;
        for (var i = 0; i < keys.length; i++) {
            var key = keys[i];
        }
        this.addChild(this.show);
    }

    return Rect;

})(module.DisplayObject);

module.Rect = Rect;