function setData(data) {
    _super.prototype.setData.call(this, data);
    var menu = data.menu || [];
    var d = new flower.ArrayValue();
    for (var i = 0; i < menu.length; i++) {
        if (menu[i].isVisible && !menu[i].isVisible(data.target, menu[i])) {
            continue;
        }
        d.push(menu[i]);
    }
    this.list.dataProvider = d;
}

function clickItem(e) {
    if (this.data.click) {
        this.data.click(this.data.target, e.data);
    }
}