function init() {
    var direction = this.data.direction;
    var d = {
        isDirection: true,
        path: "trigger",
        name: "触发器",
        menu: new software.Menu({
            menu: [
                {label: "添加触发器", type: "add"},
                {label: "删除触发器", type: "del"}
            ],
            click: function () {
                console.log(arguments)
            }
        })
    }
    direction.push(d);
}