var Bitmap = (function (_super) {

    __extends(Bitmap, _super);

    function Bitmap(data) {
        _super.call(this, data);
    }

    Bitmap.prototype.init = function () {
        this.show = new flower.Image();
        this.show.bindProperty("source", "{data.display.source}", [this]);
        this.addChild(this.show);
    }

    return Bitmap;

})(module.DisplayObject);

module.Bitmap = Bitmap;